### ISSUE TITLE
sitemap.xml missing

### ISSUE THREAD

**Issue by schmijos** [noproblan/npl-website#37]
Google Webmaster Tools beschwert sich, dass wir keine Sitemap zur Verfügung stellen. Kann man die mit dem Zend Routing automatisch erstellen?

**Comment by Chuvisco88** [comment]
Zend_Navigation sollte hier angeblich aushelfen, werde dies im Detail prüfen

**Comment by Chuvisco88** [comment]
Wir arbeiten derzeit nicht mit Page-Objekten. Was wir aber in einem ersten Schritt machen können ist die statischen Seiten in ein navigation.xml zu packen.

**Comment by schmijos** [comment]
Reviewed and merged.
