### ISSUE TITLE
Bankdaten als Text

### ISSUE THREAD

**Issue by dbrgn** [noproblan/npl-website#39]
Wär cool wenns die Bankdaten auch als Text (für copy-paste) gäbe :) Dann muss man sie nicht vom generierten Bild abtippen.

**Comment by rnestler** [comment]
+1 Hat mich auch grad geärget

**Comment by Chuvisco88** [comment]
Wurde gemerged

**Comment by rnestler** [comment]
Cool! Ist es auch schon auf npl.ch verfügbar?

**Comment by Chuvisco88** [comment]
Noch nicht, erst mit dem Deployment auf 2.0.5 :-)
Dann wird auch das Label "to deploy" wieder entfernt

**Comment by schmijos** [comment]
Ev. wäre es sinnvoller das beim Milestone zu halten und nicht beim Ticket. Das wäre weniger Arbeit. Wird ein Milestone automatisch geschlossen, wenn alle Tickets erledigt sind? Falls nein, könnte man einfach sagen, solange ein Milestone nicht geschlossen wurde, wurde auch der *master* nicht deployed.

**Comment by Chuvisco88** [comment]
Agree, war mein initialer Gedanke. Daher Ticket wird geschlossen
