### ISSUE TITLE
Vulnerability: Passwort zurücksetzen defekt

### ISSUE THREAD

**Issue by schmijos** [noproblan/npl-website#43]
> Denkt ich informier euch kurz, das d'Passwort-zrucksetz-Funktion vo eure homepage (npl.ch) defekt isch. Git me sini E-Mail Adresse ah, wird statt es Mail gsendet, en Fehlermeldig mit em E-Mail Text (inkl. link zum pw ändere/zrugsetzte?) azeigt. Weiss nid ob das öpper misbruche könnt, aber denkt ich schrieb euch kurz, falls es no niemerds gmeldet het.

**Comment by Chuvisco88** [comment]
Das Problem lag daran, dass das Mailpasswort auf dem Server nicht korrekt war, wir haben somit gar keine Mails mehr versendet...
Schliesse dieses Issue und erstelle ein neues zum Thema Error Propagation
