### ISSUE TITLE
Zertifikatprobleme bei Android Mobile Browser

### ISSUE THREAD

**Issue by schmijos** [noproblan/npl-website#45]
Der Android Mobile Browser gibt eine Zertifikat-Meldung aus sowohl bei *npl.ch* als auch bei *noproblan.ch*.

Das Problem scheint am Wochenende auch beim Firefox bestanden zu haben.

![image](https://cloud.githubusercontent.com/assets/245443/6592205/e55ef66a-c7ca-11e4-92c3-ca03da56cbf2.png)

**Comment by Chuvisco88** [comment]
Soweit ich das feststellen konnte tritt das Problem beim Android-Standardbrowser von älteren Androidgeräten auf. Bei neueren Geräten wird Chrome als Standardbrowser verwendet, da tritt das Problem nicht mehr auf.
Ich weiss nicht wirklich, ob wir hier wirklich was machen können ausser ein anderes Zertifikat zu beantragen.
