### ISSUE TITLE
Rechtesystem erweitern für Sitzplan

### ISSUE THREAD

**Issue by Chuvisco88** [noproblan/npl-website#49]
Als Teammitglied möchte ich den Sitzplan einsehen können.

Problematik derzeit liegt darin, dass die Rechte noch zu wenig granular sind und das System entsprechend zuerst überarbeitet/erweitert werden sollte.

**Comment by schmijos** [comment]
Wo konkret? Wie wäre es mit einer Session-abhängigen Action? So quasi: `mySeatMap`

Dafür haben ein Rechtekonzept.

**Comment by Chuvisco88** [comment]
Im Gegensatz zum separaten Ticket macht es vieleicht Sinn den Sitzplan im Backend anzeigbar zu machen. Dazu muss das Rechtesystem allerdings nicht erweitert werden.
Ich schlage vor, ich schliesse dieses Ticket als Duplicate zum anderen und eröffne ein neues Ticket zum Thema Sitzplan im Backend.
