### ISSUE TITLE
Anmeldung trotz Anmeldesperrung möglich

### ISSUE THREAD

**Issue by Chuvisco88** [noproblan/npl-website#53]
Erwartet: Wenn die Anmeldesperre gesetzt ist darf es nicht möglich sein sich anzumelden.

Aktuell: Bei einer LAN-Party gibt es einen Button, wenn noch niemand angemeldet ist. Dieser ist auch aktiv, wenn die Sperre aktiv ist.

**Comment by schmijos** [comment]
Sollte nicht die API eine Anmeldung verhindern anstatt ein Button?

**Comment by Chuvisco88** [comment]
True that, ich passe das Backend entsprechend noch an

**Comment by Chuvisco88** [comment]
Merged, wird somit geschlossen

**Comment by schmijos** [comment]
Naja, streng genommen müsste es auf einen Status "to_deploy" o.ä. gesetzt werden. Es ist ja noch nicht im master.
