### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by schmijos** [noproblan/npl-website#56]
Auf der Seite zur Sitzplatzreservation steht immernoch:

> Eingang ist auf der rechten Seite ca. in der Mitte. Die Bühne ist oberhalb.

Das müsste nun heissen:

> Der Eingang ist auf der rechten Seite unten. Die Turnhalle befindet sich unten.

**Comment by Chuvisco88** [comment]
Das Anpassen des Wordings bei jedem Wechsel ist eine schlechte Idee. Wir könnten ein Beschreibungsfeld für Maps hinzufügen?

**Comment by schmijos** [comment]
Agree. Aber ich denke im #v2.0.5 sollte das noch per Wording gelöst werden. Andernfalls bitte schliessen als *wontfix*

**Comment by schmijos** [comment]
Wird per #56 gelöst.
