### ISSUE TITLE
Sitzplatzreservation kaputt

### ISSUE THREAD

**Issue by dbrgn** [noproblan/npl-website#74]
https://noproblan.ch/lan/reservation/lanid/19 gibt einen HTTP 500 zurück.

**Comment by Chuvisco88** [comment]
Danke für die Info. Habe auch gleich gesehen, dass es für diese LAN noch gar keinen Sitzplatz gibt...
Werde den wohl noch erstellen müssen.

Gebe Bescheid sobald erledigt.

**Comment by Chuvisco88** [comment]
Sitzplan eingefügt, d.h. ab sofort sind Sitzplätze reservierbar :)
